<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="/style/base.css">
    <title>Student Webstore</title>
</head>
<body>
<?php if(!isset($_SESSION)): ?>
    <?php session_start(); ?>
<?php endif; ?>
<?php if(!isset($_SESSION["userId"])): ?>
    <div class="login">
        <a href="?page=cart_list">curt</a> |
        <a href="?page=customer_login">Login</a> |
        <a href="?page=customer_register">Sign Up</a>
    </div>
    <h3>Hello, please log in! </h3>
<?php else: ?>
    <div class="login">
        <a href="?page=cart_list">curt</a> |
        <a href="?page=customer_logout">Logout</a>

    </div>
    <h3>Good!!! Hello <?php echo($_SESSION["userName"]) ?> </h3>
<?php endif; ?>

<div class="page-content">
    <?php require_once __DIR__ . "/../{$view}.phtml"; ?>
</div>
</body>
</html>