<a class="page-back" href="/">&larr;</a>


<div class="login_register">

    <h1 class="page-header">
        Register Administrators!
    </h1>

    <form action="?page=admin_register" method="POST">
        <div>
            <label for="name">Name</label>
            <input type="text" id="name" name="admin[name]" />
        </div>
        <div>
            <label for="password">Password</label>
            <input type="text" id="password" name="admin[password]" />
        </div>

        <input type="submit" value="Register">
    </form>
</div>