<h1><?php echo $_SESSION['quote_id'] ?></h1>
<?php foreach ($this->get('items') as $key => $_quote): ?>
    <?php $_product = $_quote->getProduct() ?>
    <a href="?page=product_view&id=<?php echo $_product->getId(); ?>">
        <div class="products">
            <div>
                <img src="<?php echo $_product->getImage(); ?>" />
            </div>
            <div>
                <span>Name: </span>
                <h2><?php echo $_product->getName() ?></h2>
                <span>Sku: </span>
                <span><?php echo $_product->getSku() ?></span>
                <br>
                <span>Price: </span>
                <span><?php echo $_product->getPrice() ?></span>
                <br>
                <?php if ($_product->isSpecialPriceApplied()): ?>
                    <span class="special">Special Price: </span>
                    <span class="special"><?php echo $_product->getSpecialPrice()  ?></span>
                <?php endif; ?>
            </div>
        </div>
    </a>
    <br>

    <label for="count">count: <?php echo $_quote->getQty() ?> </label>
    <form action="?page=quote_delete" method="POST">
        <label for="count">count: </label>
        <input type="text" name="quote[count]" >
        <input type="text" name="quote[product_id]" value="<?php echo $_product->getId()?>" hidden>
        <input type="submit"  value="Delete" />
    </form>



<?php endforeach; ?>
<a href="?page=checkout_address">
    <input type="submit" value="Checkout" >
</a>
