<?php foreach ($products as $key => $_product): ?>
    <a href="?page=product_view&id=<?php echo $_product->getProductId(); ?>">
        <div class="products">
            <div>
                <img src="<?php echo $_product->getImage(); ?>" />
            </div>
            <div>
                <span>Name: </span>
                <h2><?php echo $_product->getName() ?></h2>
                <span>Sku: </span>
                <span><?php echo $_product->getSku() ?></span>
                <br>
                <span>Price: </span>
                <span><?php echo $_product->getPrice() ?></span>
                <br>
                <?php if ($_product->isSpecialPriceApplied()): ?>
                    <span class="special">Special Price: </span>
                    <span class="special"><?php echo $_product->getSpecialPrice()  ?></span>
                <?php endif; ?>
            </div>
        </div>
    </a>
    <br>

    <label for="count">count: <?php echo $carts[$key]['count'] ?> </label>
    <form action="?page=cart_delete" method="POST">
        <label for="count">count: </label>
        <input type="text" name="cart[count]" >
        <input type="text" name="cart[product_id]" value="<?php echo $_product->getProductId()?>" hidden>
        <input type="submit"  value="Delete" />
    </form>


<?php endforeach; ?>
