<h2>Checkout!!</h2>
<form action="?page=checkout_address" method="POST">
    <div class="address_input">
        <label for="city">City: </label>
        <select name="address[city_id]" id="city">
            <?php foreach($this->get('cities') as $_city): ?>
                <option value="<?php echo $_city->getId(); ?>"><?php echo $_city->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="address_input">
        <label for="region">Region: </label>
        <select name="address[region_id]" id="region">
            <?php foreach($this->get('regions') as $_region): ?>
                <option value="<?php echo $_region->getId(); ?>"><?php echo $_region->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="address_input">
        <label for="postal_code">Postal code: </label>
        <input type="text" name="address[postal_code]">
    </div>

    <div class="address_input">
        <label for="street">Street: </label>
        <input type="text" name="address[street]">
    </div>

    <div class="address_input">
    <label for="home_number">Home number: </label>
    <input type="text" name="address[home_number]">
    </div>

    <div class="address_input">
    <label for="flat">Flat: </label>
    <input type="text" name="address[flat]">
    </div>
    <input type="submit" value="Next"/>
</form>
