<h2>Payment!</h2>
<form action="/?page=checkout_payment" method="post">


    <?php foreach($this->get('methods') as $method): ?>
    <div class="method_shipping">
            <label><input type="radio" name="method" value="<?php echo $method->getCode() ?>">
                $ (<?php echo $method->getLabel() ?>)</label>
    </div>
        <?php endforeach; ?>

    <div><input type="submit" value="Finish"></div>
</form>