<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/style/product.css">
</head>
<body>

<div class="products">
    <div>
        <img src="<?php echo $product->getImage();?>" />
    </div>
    <div>
        <span>Name: </span>
        <h2><?php echo $product->getName() ?></h2>
        <span>Sku: </span>
        <span><?php echo $product->getSku() ?></span>
        <br>
        <span>Price: </span>
        <span><?php echo $product->getPrice() ?></span>
        <br>
        <?php if ($product->isSpecialPriceApplied()): ?>
            <span class="special">Special Price: </span>
            <span class="special"><?php echo $product->getSpecialPrice()  ?></span>
        <?php endif; ?>
    </div>

</div>
<div class="reviews">
    <h2>Reviews!</h2>
    <h3 style="color: blue"><?php echo $reviewsAll->getAverage()?></h3>
<?php foreach ($reviewsAll as $_review): ?>

        <div class="review">

            <span>Product_id: </span>
            <h2 style="color: red"><?php echo $product->getProductId() ?></h2>
            <span>Name: </span>
            <h3><?php echo $_review->getName() ?></h3>
            <span>E-mail: </span>
            <span><?php echo $_review->getEmail() ?></span>
            <br>
            <span>Description: </span>
            <span><?php echo $_review->getText() ?></span>
            <span>Rating: </span>
            <span><?php echo $_review->getRating() ?></span>
        </div>

    <br>
<?php endforeach; ?>
</div>

</body>
</html>