<div class="products">
    <div>
        <img src="<?php echo $product->getImage();?>" />
    </div>
    <div>
        <span>Name: </span>
        <h2><?php echo $product->getName() ?></h2>
        <span>Sku: </span>
        <span><?php echo $product->getSku() ?></span>
        <br>
        <span>Price: </span>
        <span><?php echo $product->getPrice() ?></span>
        <br>
        <?php if ($product->isSpecialPriceApplied()): ?>
            <span class="special">Special Price: </span>
            <span class="special"><?php echo $product->getSpecialPrice()  ?></span>
        <?php endif; ?>
    </div>pyfxtybt

</div>
<div class="reviews">
    <h2>Reviews!</h2>
    <h3 id = 'valueRating'><?php echo $reviewsAll->getAverageRating()?></h3>
<?php foreach ($reviewsAll as $_review): ?>

        <div class="review">

            <span>Product_id: </span>
            <h2 id = 'productID'><?php echo $product->getProductId() ?></h2>
            <span class="name">Name: </span>
            <h3><?php echo $_review->getName() ?></h3>
            <span class="name">E-mail: </span>
            <span class="value"><?php echo $_review->getEmail() ?></span>
            <span class="name">Description: </span>
            <span class="value"><?php echo $_review->getText() ?></span>
            <span class="name">Rating: </span>
            <span class="value"><?php echo $_review->getRating() ?></span>
        </div>

    <br>
<?php endforeach; ?>
</div>
